#pragma once
/* 用户态共享 IOCTL 号 —— 从 PowerDash.cpp 原样迁出(与 PowerDashSYS/pdstruct.h
 * 保持同一编号空间;请求结构体以 pdstruct.h 为准)。 */
#include <windows.h>

#define POWERDASH_DEV_TYPE 55000
#define IO_CTL_MSR_READ        CTL_CODE(POWERDASH_DEV_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_CTL_PCICFG_READ     CTL_CODE(POWERDASH_DEV_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_CTL_MMAP            CTL_CODE(POWERDASH_DEV_TYPE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_CTL_MUNMAP          CTL_CODE(POWERDASH_DEV_TYPE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_CTL_FNQ_INJECT      CTL_CODE(POWERDASH_DEV_TYPE, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
